// <auto-generated />
namespace ASP.NET_Practice_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class second : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(second));
        
        string IMigrationMetadata.Id
        {
            get { return "202102021835124_second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
